[tools]
zig = "master"
zls = "master"

[env]
_.path = "./.local/bin"

[tasks]
test_0_15_2 = "mise exec zig@0.15.2 -- zig build test --summary all -freference-trace=7 $@"
test_master = "mise exec zig@master -- zig build test --summary all -freference-trace=7 $@"
